# Use single quotes for strings instead of double quotes
singleQuote: true # prefer 'single quotes' for strings

# Print semicolons at the ends of statements
semi: true # add ";" at the end of every statement

# Number of spaces per indentation level
tabWidth: 2 # indent with 2 spaces

# Use spaces instead of actual tab characters
useTabs: false # false = use spaces; true = use tab characters

# Print trailing commas where valid in ES5 (objects, arrays, etc.)
trailingComma: 'es5' # possible values: 'none' | 'es5' | 'all'

# Wrap lines at this length
printWidth: 100 # maximum line length before wrapping

# Print spaces between brackets in object literals
bracketSpacing: true # { foo: bar } vs {foo: bar}

# Omit parentheses when there is a single arrow function parameter
arrowParens: 'avoid' # 'avoid' | 'always'
